# This Python file mounts the desired model with its corresponding fine-tuned adapter and allows performing inference
from huggingface_hub import login
import torch
from safetensors.torch import save_model
from federatedscope.llm.model.model_builder import get_model_from_huggingface
from federatedscope.llm.model.model_builder import get_llm
from federatedscope.llm.dataloader.dataloader import get_tokenizer
from federatedscope.core.configs.config import global_cfg
from federatedscope.llm.misc.fschat import FSChatBot

def generate_text(model, tokenizer, input_text, max_length=50, device='cpu'):
    inputs = tokenizer(input_text, return_tensors="pt").to(device)
    outputs = model.generate(**inputs, max_length=max_length)
    return tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]

# Load configuration
work_dir = "_path_to_FederatedScope_dir"
cfg_file = f"{work_dir}/_path_to_yaml_config_file"
hf_token = "your_hugging_face_token"

# Login to Hugging Face
login(hf_token)

# Write the input text to feed the model
input_text = "Tell me the capital of France."

# Initialize configuration
init_cfg = global_cfg.clone()
init_cfg.merge_from_file(cfg_file)

model_name = init_cfg.model.type.split("@")[0]
root = init_cfg.data.root
tok_len = init_cfg.llm.tok_len
model_hub = init_cfg.model.type.split("@")[1]
path_to_trained_adapt_ckpt = init_cfg.federate.save_to

# Get tokenizer and base model
tokenizer , _ = get_tokenizer(model_name, root, tok_len, model_hub)
base_model = get_model_from_huggingface(model_name, init_cfg)

# Move model to GPU if available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
base_model.to(device)

# Get base model with adapter
base_model_with_adapt = get_llm(init_cfg)
base_model_with_adapt.to(device)

""" # Generate text using the base model
generated_text = generate_text(base_model, tokenizer, input_text, device=device)
print("User: ", input_text)
print("Text generated by the base model:", generated_text)
"""

# Load trained adapter checkpoint
ckpt = torch.load(path_to_trained_adapt_ckpt, map_location='cpu', weights_only=True)

""" # Save base model + trained adapter
path_to_save_base_model_with_trained_adapt = f"{work_dir}/inference"
base_model_with_adapt.load_state_dict(ckpt['model'], strict=False)
base_model_with_adapt.save_model(f"{path_to_save_base_model_with_trained_adapt}/base_model_with_trained_adapt.ckpt") # In .ckpt
save_model(base_model_with_adapt, f"{path_to_save_base_model_with_trained_adapt}/base_model_with_trained_adapt.safetensors") # In .safetensors
"""

# Generate text using the base model + trained adapter
generated_text = generate_text(base_model_with_adapt, tokenizer, input_text, device=device)
print("User:", input_text)
print("Text generated by the model with the trained adapter:", generated_text)

# Generate text using the base model + trained adapter (FSChatBot)
fschatbot = FSChatBot(init_cfg, print_model_arch=True)
generate_kwargs = dict(max_new_tokens=init_cfg.llm.chat.max_len) 
generated_text = fschatbot.generate(input_text, generate_kwargs)
print("User:", input_text)
print("Text generated by the model with the trained adapter:", generated_text)